labels:
  - name: size/XS
    color: 3CBF00
    description: Denotes a PR that changes 0-9 lines.
    min: 0
    max: 9

  - name: size/S
    color: 5D9801
    description: Denotes a PR that changes 10-29 lines.
    min: 10
    max: 29

  - name: size/M
    color: E0B100
    description: Denotes a PR that changes 30-99 lines.
    min: 30
    max: 99

  - name: size/L
    color: D88B00
    description: Denotes a PR that changes 100-499 lines.
    min: 100
    max: 499

  - name: size/XL
    color: D86018
    description: Denotes a PR that changes 500-999 lines.
    min: 500
    max: 999

  - name: size/XXL
    color: B60205
    description: Denotes a PR that changes 1000+ lines.
    min: 1000
