export enum ServiceError {
  PARSE_ERROR = "PARSE_ERROR",

  FILE_NOT_FOUND_ERROR = "FILE_NOT_FOUND_ERROR",
  INVALID_SOURCE_PATH = "INVALID_SOURCE_PATH",
  FILE_COPY_FAILED = "FILE_COPY_FAILED",
  FILE_MOVE_FAILED = "FILE_MOVE_FAILED",
  FOLDER_CREATION_FAILED = "FOLDER_CREATION_FAILED",

  INSTANCE_NOT_FOUND_BY_ID = "INSTANCE_NOT_FOUND_BY_ID",
  EXEC_OPEN_DIR_ERROR = "EXEC_OPEN_DIR_ERROR",
  SERVER_NBT_READ_ERROR = "SERVER_NBT_READ_ERROR",

  FETCH_ERROR = "FETCH_ERROR",
  INVALID_CODE = "INVALID_CODE",
  CODE_EXPIRED = "CODE_EXPIRED",
  VERSION_MISMATCH = "VERSION_MISMATCH",

  DUPLICATE = "DUPLICATE",
  INVALID = "INVALID",
  NOT_FOUND = "NOT_FOUND",
  TEXTURE_ERROR = "TEXTURE_ERROR",
  AUTH_SERVER_ERROR = "AUTH_SERVER_ERROR",
  CANCELLED = "CANCELLED",
}
