use crate::error::SJMCLResult;
use crate::instance::export::common::ExportModpackOptions;
use crate::instance::models::misc::{Instance, ModLoaderType};
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MultiMCManifest {
  pub format_version: u32,
  pub components: Vec<MultiMCComponent>,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MultiMCComponent {
  pub uid: String,
  pub version: String,
  pub important: bool,
  pub dependency_only: bool,
}

/// Generate a MultiMC format manifest for the instance
pub fn generate_multimc_manifest(
  instance: &Instance,
  _options: &ExportModpackOptions,
) -> SJMCLResult<MultiMCManifest> {
  let mut components = Vec::new();

  // Add Minecraft component (always important)
  components.push(MultiMCComponent {
    uid: "net.minecraft".to_string(),
    version: instance.version.clone(),
    important: true,
    dependency_only: false,
  });

  // Add mod loader component if present
  if instance.mod_loader.loader_type != ModLoaderType::Unknown {
    let version = &instance.mod_loader.version;
    let uid = match instance.mod_loader.loader_type {
      ModLoaderType::Forge | ModLoaderType::LegacyForge => "net.minecraftforge",
      ModLoaderType::NeoForge => "net.neoforged",
      ModLoaderType::Fabric => "net.fabricmc.fabric-loader",
      ModLoaderType::Quilt => "org.quiltmc.quilt-loader",
      _ => "",
    };

    if !uid.is_empty() {
      components.push(MultiMCComponent {
        uid: uid.to_string(),
        version: version.clone(),
        important: false,
        dependency_only: false,
      });
    }
  }

  Ok(MultiMCManifest {
    format_version: 1,
    components,
  })
}

/// Generate instance.cfg file content for MultiMC
pub fn generate_multimc_instance_cfg(
  instance: &Instance,
  options: &ExportModpackOptions,
) -> String {
  format!(
    "# Auto generated by SJMC Launcher\nInstanceType=OneSix\nname={}\n",
    options.name
  )
}
